# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: cma-aws
image:
  repo: registry.gitlab.com/mvenezia/cma-aws:branch-master-94351450

port: 80
service:
  port: 80
  type: ClusterIP
ingress:
  rest:
    name: cma-aws
    host: cma-aws.ontario.cluster.cnct.io
  grpc:
    name: cma-aws-grpc
    host: cma-aws-grpc.ontario.cluster.cnct.io
issuer:
  email: mvenezia@gmail.com
  region: us-east-1
